### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jonataswalker**
Can't use Vue 2.1.8 with your plugin, message is:

Vue packages version mismatch:
- vue@2.1.8
- vue-template-compiler@2.1.6

### CODE REVIEW

**Comment by thgh** [comment]
This PR would force everyone to use the latest Vue version. `^2.1.3` means that this plugin works with every Vue version above 2.1.3.

You can resolve the mismatch by setting a fixed version in your package.json. For example:
```
"vue": "2.1.8",
"vue-template-compiler": "2.1.8",
```

Node.js should then use the specified version for this plugin.

**Comment by thgh** [comment]
It's however not a bad idea to follow the devDepencendies, so I will merge it :-)

**Comment by jonataswalker** [comment]
@thgh Any chance for a new version publishing?

**Comment by thgh** [comment]
Alright, it's done!

**Pull request merged**
